title : Marco A. Gutiérrez
description: 'Marco A. Gutiérrez'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins: [jekyll-gist]
plugins: [jekyll-scholar]
plugins: [jekyll-paginate]
permalink: /:year/:month/:title.html
